/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.TimeUnit;

import com.formkiq.client.api.DocumentWorkflowsApi;
import com.formkiq.client.api.DocumentsApi;
import com.formkiq.client.api.RulesetsApi;
import com.formkiq.client.invoker.ApiClient;
import com.formkiq.client.invoker.ApiException;
import com.formkiq.client.model.AddDocumentRequest;
import com.formkiq.client.model.AddQueueRequest;
import com.formkiq.client.model.AddRule;
import com.formkiq.client.model.AddRuleRequest;
import com.formkiq.client.model.AddRuleset;
import com.formkiq.client.model.AddRulesetRequest;
import com.formkiq.client.model.AddRulesetResponse;
import com.formkiq.client.model.AddWorkflowRequest;
import com.formkiq.client.model.AddWorkflowStep;
import com.formkiq.client.model.AddWorkflowStepQueue;
import com.formkiq.client.model.GetWorkflowQueueDocumentsResponse;
import com.formkiq.client.model.RuleCondition;
import com.formkiq.client.model.RuleConditionAttribute;
import com.formkiq.client.model.RuleConditionMust;
import com.formkiq.client.model.RuleConditionOperation;
import com.formkiq.client.model.RulesetStatus;
import com.formkiq.client.model.WorkflowDocument;
import com.formkiq.client.model.WorkflowStatus;

public class App {

	private static final String ACCESS_TOKEN = "<ACCESS_TOKEN>";
	private static final String HTTP_API_URL = "<CloudFormation Outputs HttpApiUrl>";

	private static final String QUEUE_A = "queueA";
	private static final String QUEUE_B = "queueB";

	private DocumentWorkflowsApi workflowsApi;
	private RulesetsApi rulesetsApi;
	private DocumentsApi documentsApi;

	public static void main(String[] args) throws ApiException, InterruptedException {

		String siteId = null;

		App app = new App();
		app.setUpApi();

		String queueAId = app.createQueue(siteId, QUEUE_A);
		String queueBId = app.createQueue(siteId, QUEUE_B);

		String workflowAId = app.createQueueWorkflow(siteId, queueAId, QUEUE_A, "finance");
		String workflowBId = app.createQueueWorkflow(siteId, queueBId, QUEUE_B, "management");

		app.createRuleset(siteId, workflowAId, workflowBId);

		app.addDocument(siteId, "test data", "text/plain");
		app.addDocument(siteId, "{\"content\":\"test data\"}", "application/json");

		List<WorkflowDocument> documentsInQueueA = app.getDocumentsInQueue(siteId, queueAId);
		System.out.println("# of documents in queue: " + documentsInQueueA.size());
		System.out.println("content type: " + documentsInQueueA.get(0).getDocument().getContentType());

		List<WorkflowDocument> documentsInQueueB = app.getDocumentsInQueue(siteId, queueBId);
		System.out.println("# of documents in queue: " + documentsInQueueB.size());
		System.out.println("content type: " + documentsInQueueB.get(0).getDocument().getContentType());
	}

	private String createQueue(String siteId, String queueName) throws ApiException {
		return workflowsApi.addQueue(new AddQueueRequest().name(queueName), siteId).getQueueId();
	}

	/**
	 * Setup API classes.
	 */
	public void setUpApi() {

		ApiClient client = (new ApiClient()).setReadTimeout(0).setBasePath(HTTP_API_URL);
		client.addDefaultHeader("Authorization", ACCESS_TOKEN);
		workflowsApi = new DocumentWorkflowsApi(client);
		rulesetsApi = new RulesetsApi(client);
		documentsApi = new DocumentsApi(client);
	}

	/**
	 * Get Documents in Queue. Could take a few seconds for documents to be
	 * processed.
	 */
	private List<WorkflowDocument> getDocumentsInQueue(final String siteId, final String queueId)
			throws ApiException, InterruptedException {

		final int maxWait = 10;
		int waitCount = 0;
		List<WorkflowDocument> documents = null;

		do {

			GetWorkflowQueueDocumentsResponse response = workflowsApi.getWorkflowQueueDocuments(queueId, siteId, null,
					null);
			documents = response.getDocuments();

			if (documents.isEmpty()) {
				TimeUnit.SECONDS.sleep(1);
				waitCount++;

				if (waitCount > maxWait) {
					throw new InterruptedException();
				}
			}

		} while (documents.isEmpty());

		return documents;
	}

	/**
	 * Create Document with specific content and content-type.
	 */
	private String addDocument(final String siteId, final String content, final String contentType)
			throws ApiException {
		AddDocumentRequest req = new AddDocumentRequest().content(content).contentType(contentType);
		return documentsApi.addDocument(req, siteId, null).getDocumentId();
	}

	/**
	 * Create Workflow that places documents into a Queue.
	 */
	public String createQueueWorkflow(final String siteId, final String queueId, final String queueName,
			final String approvalRole) throws ApiException {

		// Create Workflow Step
		AddWorkflowStep step0 = new AddWorkflowStep().stepId(UUID.randomUUID().toString())
				.queue(new AddWorkflowStepQueue().queueId(queueId).addApprovalGroupsItem(approvalRole));

		// Create Add Workflow Request
		AddWorkflowRequest req = new AddWorkflowRequest().name("Queue " + queueName).description("Queue " + queueName)
				.status(WorkflowStatus.ACTIVE).addStepsItem(step0);

		return workflowsApi.addWorkflow(req, siteId).getWorkflowId();
	}

	/**
	 * Create Rule based on document Content-Type.
	 */
	private void createContentTypeRule(final String siteId, String rulesetId, final String workflowId,
			final String contentType) throws ApiException {
		AddRule addRule = new AddRule().description("Workflow " + workflowId).workflowId(workflowId)
				.status(RulesetStatus.ACTIVE)
				.conditions(new RuleCondition()
						.addMustItem(new RuleConditionMust().attribute(RuleConditionAttribute.CONTENT_TYPE)
								.value(contentType).operation(RuleConditionOperation.EQ)));
		AddRuleRequest req = new AddRuleRequest().rule(addRule);

		rulesetsApi.addRule(rulesetId, req, siteId);
	}

	/**
	 * Create Ruleset with Content-Type rules.
	 */
	public void createRuleset(final String siteId, final String workflowAId, String workflowBId) throws ApiException {

		String rulesetId = createRuleset(siteId);

		createContentTypeRule(siteId, rulesetId, workflowAId, "application/json");
		createContentTypeRule(siteId, rulesetId, workflowBId, "text/plain");
	}

	/**
	 * Create Ruleset.
	 */
	public String createRuleset(final String siteId) throws ApiException {
		AddRulesetRequest req = new AddRulesetRequest().ruleset(new AddRuleset().description("Ruleset 1")
				.priority(new BigDecimal(1)).version(new BigDecimal(1)).status(RulesetStatus.ACTIVE));

		AddRulesetResponse addRuleset = rulesetsApi.addRuleset(req, siteId);

		return addRuleset.getRulesetId();
	}
}
